### ISSUE TITLE
ranger + gzip sometimes gives errors CorruptInputError

### ISSUE THREAD

**Issue by vtolstov** [DHowett/ranger#2]
I'm try to use  ranger with compressed gzip file via http.
When i don't change BlockSize all works fine, but then i increase block size to 4 Mb, i have errors.
In case of increased ranger BlockSize my trivial code (create gzip.NewReader from ranger and io.Copy from gzip.Reader to file) gives error flate.CorruptInputError

**Comment by DHowett** [comment]
Does this happen with any gzip file? How large is it?

**Comment by vtolstov** [comment]
I'm tr with file about 300Mb, my issue may be related with pgzip and bgzf that tryes to decompress file in parallel.

**Comment by DHowett** [comment]
I'm going to close this due to lack of information; if you keep hitting it, would you mind grabbing a trace we can look at?
Thanks!
